validate input

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -2,6 +2,12 @@ name: 'publish'
 
 on:
   workflow_dispatch:
+    inputs:
+      version_bump:
+        description: 'Confirm tauri.conf.json > version has been updated'
+        required: true
+        type: boolean
+        default: false
 
 jobs:
   publish:
@@ -15,7 +21,7 @@ jobs:
             args: '--target aarch64-apple-darwin'
           - platform: 'macos-latest'
             args: '--target x86_64-apple-darwin'
-          - platform: 'ubuntu-20.04'
+          - platform: 'ubuntu-latest'
             args: ''
           - platform: 'windows-latest'
             args: ''
@@ -23,6 +29,13 @@ jobs:
     runs-on: ${{ matrix.platform }}
     steps:
       - uses: actions/checkout@v5
+
+      - name: check version update
+        run: |
+          if [[ "${{ github.event.inputs.version_bump }}" != "true" ]]; then
+            echo "Error: You must increment tauri.conf.json version"
+            exit 1
+          fi
 
       - name: setup node
         uses: actions/setup-node@v4
@@ -41,7 +54,7 @@ jobs:
           workspaces: './src-tauri -> target'
 
       - name: install dependencies (ubuntu only)
-        if: matrix.platform == 'ubuntu-20.04' # This must match the platform value defined above.
+        if: matrix.platform == 'ubuntu-latest' # This must match the platform value defined above.
         run: |
           sudo apt-get update
           sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
